from PyQt5 import QtCore, QtGui, QtWidgets
import qt_ui

#DO NOT MODIFY CODE GENERATED BY QTDESIGNER
#THIS CLASS ENABLES YOU TO ADD FUNCTIONS TO USE THE UI
class AdditionWindow(QtWidgets.QDialog):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) #enables class to operate as the dialog

        self.ui = qt_ui.Ui_Dialog()
        self.ui.setupUi(self)

        self.ui.Button_1.clicked.connect(self.addition) #assigns the callback fcn of button

    def addition(self):

        num1 = self.ui.num_1.text()
        num2 = self.ui.num_2.text()
        res = int(num1) + int(num2)

        self.ui.result.setText(str(res))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication([])

    dialog = AdditionWindow()
    dialog.show()

    app.exec_()