#ifndef ORDER_H
#define ORDER_H

// Define the orders that can be sent and received
enum Order {

  // DOIT ÊTRE EXACTEMENT LA MÊME LIST/ORDRE QUE DANS LE PROG PYTHON

  //ORDRE GÉNÉRAL
    HELLO = 0,
    ALREADY_CONNECTED = 1,
    ERROR = 2,
    RECEIVED = 3,
    FINISHED = 4,

    HOME = 5,
    START = 6,
    STOP = 7,
    SEMI_AUTO_ANGLE = 8,
    SEMI_AUTO_STATE = 9,
    SERVO_AVANT_DROIT = 10,
    SERVO_AVANT_GAUCHE = 11,
    SERVO_ARRIERE_DROIT = 12,
    SERVO_ARRIERE_GAUCHE = 13,
    MOTEUR_AVANT_DROIT = 14,
    MOTEUR_AVANT_GAUCHE = 15,
    MOTEUR_ARRIERE_DROIT = 16,
    MOTEUR_ARRIERE_GAUCHE = 17,
    ELECTROAIMANT_AVANT_DROIT = 18,
    ELECTROAIMANT_AVANT_GAUCHE = 19,
    ELECTROAIMANT_ARRIERE_DROIT = 20,
    ELECTROAIMANT_ARRIERE_GAUCHE = 21,
  
};

typedef enum Order Order;

#endif
